export const BILLING_TIERS = [
  {
    key: 'premium',
    offeringId: 'premium',
    productId: 'premium',
    tier: 3,
    testId: 'paywall.tier.premium',
    label: 'Premium',
    eyebrow: 'BUNDLE',
    image: require('../../assets/categories/all-image-cat.webp'),
    features: ['Create and own private groups', 'Remove mandatory ads', 'All core game modes'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: true,
  },
  {
    key: 'private_group_creator',
    offeringId: 'private_group_creator_offering',
    productId: 'private_group_creator',
    tier: 2,
    testId: 'paywall.tier.private-group-creator',
    label: 'Private Group',
    eyebrow: 'PRIVATE',
    image: require('../../assets/home/WoIstWaldo-character-hide.webp'),
    features: ['Create and own private groups', 'Invite-only private rooms', 'Up to 30 members per group'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: false,
  },
  {
    key: 'no_ads',
    offeringId: 'no_ads_offering',
    productId: 'no_ads',
    tier: 1,
    testId: 'paywall.tier.no-ads',
    label: 'No Ads',
    eyebrow: 'AD-FREE',
    image: require('../../assets/home/WoIstWaldo-character-stats.webp'),
    features: ['Remove all ads', 'Uninterrupted play', 'Faster rounds'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: false,
  },
];
