export const BILLING_TIERS = [
  {
    key: 'private_group_extension',
    offeringId: 'private_group_extension_offering',
    productId: 'private_group_extension',
    tier: 3,
    testId: 'paywall.tier.private-group-extension',
    label: 'Extended Group',
    eyebrow: 'EXTENDED',
    image: require('../../assets/categories/all-image-cat.webp'),
    features: ['Host larger group games', '10 more player slots', 'All core game modes'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: false,
  },
  {
    key: 'private_group_creator',
    offeringId: 'private_group_creator_offering',
    productId: 'private_group_creator',
    tier: 2,
    testId: 'paywall.tier.private-group-creator',
    label: 'Private Group',
    eyebrow: 'PRIVATE',
    image: require('../../assets/home/WoIstWaldo-character-hide.webp'),
    features: ['Invite-only private rooms', 'You stop seeing mandatory ads', '10 members per room'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: true,
  },
  {
    key: 'no_ads',
    offeringId: 'no_ads_offering',
    productId: 'no_ads',
    tier: 1,
    testId: 'paywall.tier.no-ads',
    label: 'No Ads',
    eyebrow: 'AD-FREE',
    image: require('../../assets/home/WoIstWaldo-character-stats.webp'),
    features: ['Remove all ads', 'Uninterrupted play', 'Faster rounds'],
    priceSuffix: '/month',
    isSubscription: true,
    ctaText: 'Subscribe',
    featured: false,
  },
];
